### ISSUE TITLE
RedisBungee compatibility

### ISSUE THREAD

**Issue by minecraft7net** [AuthMe/AuthMeBungee#21] opened 2018-02-06 15:44 UTC
[16:41:46] [main/INFO]: Enabled Waterfall version git:Waterfall-Bootstrap:1.12-SNAPSHOT:87b23b8:165
laterst waterfall build / b165

[16:41:46] [main/INFO]: Loaded plugin AuthMeBungee version 2.0.1-SNAPSHOT by null
[16:41:47] [main/INFO]: Enabled plugin AuthMeBungee version 2.0.1-SNAPSHOT by null

https://pastebin.com/gZDyG9d6

"..."
[10:30:24] [Netty Worker IO Thread #0/WARN] [global]: Error dispatching event PluginMessageEvent(super=TargetedEvent(sender=net.md_5.bungee.ServerConnection@55b01c03, receiver=Sedirus), cancelled=true, tag=BungeeCord) to listener fr.xephi.authmebungee.listeners.BungeeMessageListener@315d228d
java.lang.NullPointerException: null
        at fr.xephi.authmebungee.listeners.BungeeMessageListener.handleOnLogin(BungeeMessageListener.java:80) ~[?:?]
        at fr.xephi.authmebungee.listeners.BungeeMessageListener.onPluginMessage(BungeeMessageListener.java:69) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor108.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]

"..."

Spigot - auth server plugins:

[16:05:24] [Server thread/INFO]: [AuthMe] Loading AuthMe v5.4.0-b1877

**Comment by minecraft7net** [comment] 2018-02-06 15:46
and my environment is:

2 x bungeecoord with redisbungee + authmebungee + fastlogin
2 x authservers with authme

**Comment by sgdc3** [comment] 2018-02-06 20:58
The plugin isn't compatible with redisbungee atm

**Comment by minecraft7net** [comment] 2018-02-06 21:22
env update 

bungeecord:
[19:26:11] [main/INFO]: Loaded plugin FastLogin version 1.11-e5e815a by games647, https://github.com/games647/FastLogin/graphs/contributors
AuthMeBungee - curently disabled - waiting for redisbungee support

spigot authservers:
[20:05:58] [Server thread/INFO]: [AuthMe] Loading AuthMe v5.5.0-SNAPSHOT-b1969

**Comment by sgdc3** [comment] 2021-04-08 22:42
Duplicate of #66

**Closed as completed by sgdc3** 2021-04-08 22:42 UTC
Labels: enhancement
